security:
  oauth2:
    client:
      clientId: 535119393515869
      clientSecret: 263a5e711ed613b180c0aa9b82e58373
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me